Changed master nodes to controlplane
UKCloud/openshift-upi-ansible pull request #7
Opened 2021-01-06 10:44 UTC by koneill94

Masters are now deployed as controlplane nodes. Tested a deployment.

2021-01-06 10:56 UTC, stevemul requested changes
Some more areas that need changed - might as well clean the whole lot up when we're doing this for the sake of consistency if possible.

2021-01-06 10:56 UTC, stevemul commented on common.yaml
> +      os_sg_master: "{{ infraID }}-controlplane"
```suggestion
      os_sg_controlplane: "{{ infraID }}-controlplane"
```

2021-01-06 10:56 UTC, stevemul commented on common.yaml
> +      os_sg_master: "{{ infraID }}-controlplane"
I'm sure this change would cascade through elsewhere, but if we're changing it in one place might as well remove the term throughout the code base if we can?

2021-01-06 10:56 UTC, stevemul commented on master.sh
> +json.dump(ignition, sys.stdout)" <master.ign >"$INFRA_ID-controlplane-$index-ignition.json"
I assume master.ign is a filename that the installer generates?

2021-01-06 10:56 UTC, stevemul commented on server-groups.yaml
>    - name: Create master server group
```suggestion
  - name: Create control plane server group
```

2021-01-08 09:29 UTC, gellner approved these changes
LGTM

2021-01-08 09:56 UTC, koneill94 commented
@stevemul Can you take another look? Changes made in response to your comments.

2021-01-11 10:09 UTC, stevemul approved these changes
Provided it's been tested and works still then LGTM.

2021-01-12 11:47 UTC, merged